syntax = "proto2";

package ebl_api;

option go_package = "ebl_api";

import "api.proto";


message LoginReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}

message LoginResp {
  required int64 code = 1;
  required string message = 2;
  optional LoginData data = 3;
}

message LoginData{
  required string token = 1;
}

message CreateCompanyReq {
  required string company_code = 1[(api.body)="company_code"];
  required string company_name = 2[(api.body)="company_name"];
  required CompanyType company_type = 3[(api.body)="company_type"];
  required string admin_email = 4[(api.body)="admin_email"];
  required string admin_password = 5[(api.body)="admin_password"];
  required string admin_name = 6[(api.body)="admin_name"];
}

message CreateCompanyResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateCompanyData data = 3;
}

message CreateCompanyData{
  required int64 id = 1;
}

message GetUserInfoReq {
}

message GetUserInfoResp {
  required int64 code = 1;
  required string message = 2;
  optional GetUserInfoData data = 3;
}

message GetUserInfoData{
  required int64 user_id = 1;
  required string user_email = 2;
  required string user_name = 3;
  required UserType user_type = 4;
  required int64 company_id = 5;
  required string company_name = 6;
  required string company_code = 7;
  required CompanyType company_type = 8;
}

message GetCompanyAllListReq {
}

message GetCompanyAllListResp {
  required int64 code = 1;
  required string message = 2;
  optional GetCompanyAllListData data = 3;
}

message GetCompanyAllListData{
  repeated Company company_list = 1;
}

message CreateEblReq {
  required Ebl ebl = 1;
}

message CreateEblResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateEblData data = 3;
}

message CreateEblData{
  required int64 id = 1;
}

message QueryAllEblListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required string bookmark = 2[(api.body)="bookmark"];
}

message QueryAllEblListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryAllEblListData data = 3;
}

message QueryAllEblListData{
  repeated Ebl ebl_list = 1;
  required int64 fetchedRecordsCount = 2;
  required string bookmark = 3;
}

message QueryEblListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required string bookmark = 2[(api.body)="bookmark"];
  required Ebl ebl = 3[(api.body)="ebl"];
}

message QueryEblListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryEblListData data = 3;
}

message QueryEblListData{
  repeated Ebl ebl_list = 1;
  required int64 fetchedRecordsCount = 2;
  required string bookmark = 3;
}

message SubmitEblReq {
  required string eblNo = 1[(api.body)="eblNo"];
}

message SubmitEblResp {
  required int64 code = 1;
  required string message = 2;
  optional SubmitEblData data = 3;
}

message SubmitEblData{
  required int64 id = 1;
}

service EblApi {

  rpc Login(LoginReq) returns(LoginResp) {
    option (api.post) = "/user/login";
  }

  rpc CreateCompany(CreateCompanyReq) returns(CreateCompanyResp) {
    option (api.post) = "/company/create";
  }

  rpc GetUserInfo(GetUserInfoReq) returns(GetUserInfoResp) {
    option (api.get) = "/user/info";
  }

  rpc GetCompanyAllList(GetCompanyAllListReq) returns(GetCompanyAllListResp) {
    option (api.get) = "/company/all";
  }

  rpc CreateEbl(CreateEblReq) returns(CreateEblResp) {
    option (api.post) = "/ebl/create";
  }

  rpc QueryAllEblList(QueryAllEblListReq) returns(QueryAllEblListResp) {
    option (api.post) = "/ebl/all";
  }

  rpc QueryEblList(QueryEblListReq) returns(QueryEblListResp) {
    option (api.post) = "/ebl/query";
  }

  rpc SubmitEbl(SubmitEblReq) returns(SubmitEblResp) {
    option (api.post) = "/ebl/submit";
  }
}
enum CompanyType {
  Ship = 1;
  Bank = 2;
  Common = 3;
}

enum UserType {
  Admin = 1;
  User = 2;
}

message Company {
  required int64 id = 1;
  required string company_code = 2;
  required string company_name = 3;
  required CompanyType company_type = 4;
}


message Ebl {
  required string eblNo = 1;
  required string originCompanyID = 2;
  required string originCompanyName = 3;
  required string shipperCompanyID = 4;
  required string shipperCompanyName = 5;
  required string consigneeCompanyID = 6;
  required string consigneeCompanyName = 7;
  required string notifyPartyCompanyID = 8;
  required string notifyPartyCompanyName = 9;
  required string placeOfReceipt = 10;
  required string oceanVessel = 11;
  required string portOfLoading = 12;
  required string portOfDescharge = 13;
  required string placeOfDestination = 14;
  required string placeOfDelivery = 15;
  required string shippingMarkes = 16;
  required double quantityOfPackages = 17;
  required string kindOfPackagesGW = 18;
  required string kindOfPackagesM = 19;
  required string descriptionOfGoods = 20;
  required double grossWeight = 21;
  required double measurement = 22;
  required string freightAndCharges = 23;
  required string placeOfIssue = 24;
  required int64 dateOfIssue = 25;
  required string deliveryAgent = 26;
  required int64 shippedOnBoard = 27;
  required int64 numOfEBL = 28;
  required int64 dateOfIssueDeadline = 29;
  required string status = 30;
  required string file = 31;
  repeated string contractFiles = 32;
  repeated string invoiceFiles = 33;
  required string transferCompanyID = 34;
  required string transferCompanyName = 35;
  required int64 companyID = 36;
  required string companyName = 37;
}