syntax = "proto2";

package ebl_api;

option go_package = "ebl_api";

import "api.proto";

message SignUpReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}

message SignUpResp {
  required int64 code = 1;
  required string message = 2;
  optional SignUpData data = 3;
}

message SignUpData {
    required int64 id = 1;
}

message LoginReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}

message LoginResp {
  required int64 code = 1;
  required string message = 2;
  optional LoginData data = 3;
}

message LoginData{
  required string token = 1;
}

service EblApi {
  rpc SignUp(SignUpReq) returns(SignUpResp) {
    option (api.post) = "/user/signup";
  }

  rpc Login(LoginReq) returns(LoginResp) {
    option (api.post) = "/user/login";
  }
}
