syntax = "proto2";

package ebl_api;

option go_package = "ebl_api";

import "api.proto";

message LoginReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}

message LoginResp {
  required int64 code = 1;
  required string message = 2;
  optional LoginData data = 3;
}

message LoginData{
  required string token = 1;
}

message CreateCompanyReq {
  required string company_code = 1[(api.body)="company_code"];
  required string company_name = 2[(api.body)="company_name"];
  required CompanyType company_type = 3[(api.body)="company_type"];
  required string admin_email = 4[(api.body)="admin_email"];
  required string admin_password = 5[(api.body)="admin_password"];
  required string admin_name = 6[(api.body)="admin_name"];
}

message CreateCompanyResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateCompanyData data = 3;
}

message CreateCompanyData{
  required int64 id = 1;
}

message CreateCompanyUserReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
  required string name = 3[(api.body)="name"];
  required UserType user_type = 4[(api.body)="user_type"];
}

message CreateCompanyUserResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateCompanyUserData data = 3;
}

message CreateCompanyUserData{
  required int64 id = 1;
}

message GetUserInfoReq {
}

message GetUserInfoResp {
  required int64 code = 1;
  required string message = 2;
  optional GetUserInfoData data = 3;
}

message GetUserInfoData{
  required int64 user_id = 1;
  required string user_email = 2;
  required string user_name = 3;
  required UserType user_type = 4;
  required int64 company_id = 5;
  required string company_name = 6;
  required string company_code = 7;
  required CompanyType company_type = 8;
}

message GetCompanyAllListReq {
}

message GetCompanyAllListResp {
  required int64 code = 1;
  required string message = 2;
  optional GetCompanyAllListData data = 3;
}

message GetCompanyAllListData{
  repeated Company company_list = 1;
}

message CreateEblReq {
  required Ebl ebl = 1;
}

message CreateEblResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateEblData data = 3;
}

message CreateEblData{
  required int64 id = 1;
}

message QueryAllEblListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required string bookmark = 2[(api.body)="bookmark"];
}

message QueryAllEblListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryAllEblListData data = 3;
}

message QueryAllEblListData{
  repeated EblExtra ebl_list = 1;
  required int64 fetchedRecordsCount = 2;
  required string bookmark = 3;
}

message QueryEblListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required string bookmark = 2[(api.body)="bookmark"];
  required EblFilter ebl = 3[(api.body)="ebl"];
  required QueryEblType type = 4[(api.body)="type"];
}

message QueryEblListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryEblListData data = 3;
}

message QueryEblListData{
  repeated EblExtra ebl_list = 1;
  required int64 fetchedRecordsCount = 2;
  required string bookmark = 3;
}

message QueryEblTransferLogReq {
  required string eblNo = 1[(api.body)="eblNo"];
}

message QueryEblTransferLogResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryEblTransferLogData data = 3;
}

message QueryEblTransferLogData{
  repeated EblTransferLog ebl_transfer_log_list = 1;
}

message OperateEblReq {
  required string eblNo = 1[(api.body)="eblNo"];
  required OperationType type = 2[(api.body)="type"];
  optional int64 transferCompanyID = 3[(api.body)="transferCompanyID"];
  optional int64 sealId = 4[(api.body)="sealId"];
}

message OperateEblResp {
  required int64 code = 1;
  required string message = 2;
  optional OperateEblData data = 3;
}

message OperateEblData{
}

message UploadSealReq {
}

message UploadSealResp {
  required int64 code = 1;
  required string message = 2;
  optional UploadSealData data = 3;
}

message UploadSealData{
  required int64 id = 1;
}

message QuerySealReq {
}

message QuerySealResp {
  required int64 code = 1;
  required string message = 2;
  optional QuerySealData data = 3;
}

message QuerySealData{
  repeated CompanySeal seal_list = 1;
}

message DeleteSealReq {
  required int64 id = 1;
}

message DeleteSealResp {
  required int64 code = 1;
  required string message = 2;
  optional DeleteSealData data = 3;
}

message DeleteSealData{
}

message CheckTokenReq {
}

message CheckTokenResp {
  required int64 code = 1;
  required string message = 2;
  optional CheckTokenData data = 3;
}

message CheckTokenData{
}

message CreateInvoiceReq {
  required Invoice invoice = 1;
}

message CreateInvoiceResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateInvoiceData data = 3;
}

message CreateInvoiceData{
  required int64 id = 1;
}

message CreateContractReq {
  required Contract contract = 1;
}

message CreateContractResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateContractData data = 3;
}

message CreateContractData{
  required int64 id = 1;
}

message CreateDocumentReq {
  required Document document = 1;
}

message CreateDocumentResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateDocumentData data = 3;
}

message CreateDocumentData{
  required int64 id = 1;
}

message QueryInvoiceListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required int64 page_number = 2[(api.body)="page_number"];
  optional InvoiceFilter invoice = 3[(api.body)="invoice"];
}

message QueryInvoiceListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryInvoiceListData data = 3;
}

message QueryInvoiceListData{
  repeated Invoice invoice_list = 1;
  required int64 total = 2;
}

message QueryContractListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required int64 page_number = 2[(api.body)="page_number"];
  optional ContractFilter contract = 3[(api.body)="contract"];
}

message QueryContractListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryContractListData data = 3;
}

message QueryContractListData{
  repeated Contract contract_list = 1;
  required int64 total = 2;
}

message QueryDocumentListReq {
  required int64 page_size = 1[(api.body)="page_size"];
  required int64 page_number = 2[(api.body)="page_number"];
  optional DocumentFilter document = 3[(api.body)="document"];
}

message QueryDocumentListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryDocumentListData data = 3;
}

message QueryDocumentListData{
  repeated Document document_list = 1;
  required int64 total = 2;
}

message GetInvoiceReq {
  required int64 id = 1;
}

message GetInvoiceResp {
  required int64 code = 1;
  required string message = 2;
  optional GetInvoiceData data = 3;
}

message GetInvoiceData{
  required Invoice invoice = 1;
}

message GetContractReq {
  required int64 id = 1;
}

message GetContractResp {
  required int64 code = 1;
  required string message = 2;
  optional GetContractData data = 3;
}

message GetContractData{
  required Contract contract = 1;
}

message GetDocumentReq {
  required int64 id = 1;
}

message GetDocumentResp {
  required int64 code = 1;
  required string message = 2;
  optional GetDocumentData data = 3;
}

message GetDocumentData{
  required Document document = 1;
}

service EblApi {

  rpc Login(LoginReq) returns(LoginResp) {
    option (api.post) = "/user/login";
  }
  rpc CreateCompany(CreateCompanyReq) returns(CreateCompanyResp) {
    option (api.post) = "/company/create";
  }
  rpc GetUserInfo(GetUserInfoReq) returns(GetUserInfoResp) {
    option (api.get) = "/user/info";
  }
  rpc GetCompanyAllList(GetCompanyAllListReq) returns(GetCompanyAllListResp) {
    option (api.get) = "/company/all";
  }
  rpc CreateEbl(CreateEblReq) returns(CreateEblResp) {
    option (api.post) = "/ebl/create";
  }
  rpc QueryAllEblList(QueryAllEblListReq) returns(QueryAllEblListResp) {
    option (api.post) = "/ebl/all";
  }
  rpc QueryEblList(QueryEblListReq) returns(QueryEblListResp) {
    option (api.post) = "/ebl/query";
  }
  rpc OperateEbl(OperateEblReq) returns(OperateEblResp) {
    option (api.post) = "/ebl/operate";
  }
  rpc UploadSeal(UploadSealReq) returns(UploadSealResp) {
    option (api.post) = "/company/seal/upload";
  }
  rpc CheckToken(CheckTokenReq) returns(CheckTokenResp) {
    option (api.post) = "/user/check";
  }
  rpc CreateInvoice(CreateInvoiceReq) returns(CreateInvoiceResp) {
    option (api.post) = "/invoice/create";
  }
  rpc CreateContract(CreateContractReq) returns(CreateContractResp) {
    option (api.post) = "/contract/create";
  }
  rpc CreateDocument(CreateDocumentReq) returns(CreateDocumentResp) {
    option (api.post) = "/document/create";
  }
  rpc QueryInvoiceList(QueryInvoiceListReq) returns(QueryInvoiceListResp) {
    option (api.post) = "/invoice/query";
  }
  rpc QueryContractList(QueryContractListReq) returns(QueryContractListResp) {
    option (api.post) = "/contract/query";
  }
  rpc QueryDocumentList(QueryDocumentListReq) returns(QueryDocumentListResp) {
    option (api.post) = "/document/query";
  }
  rpc GetInvoice(GetInvoiceReq) returns(GetInvoiceResp) {
    option (api.post) = "/invoice/get";
  }
  rpc GetContract(GetContractReq) returns(GetContractResp) {
    option (api.post) = "/contract/get";
  }
  rpc GetDocument(GetDocumentReq) returns(GetDocumentResp) {
    option (api.post) = "/document/get";
  }
  rpc QuerySeal(QuerySealReq) returns(QuerySealResp) {
    option (api.get) = "/company/seal/query";
  }
  rpc DeleteSeal(DeleteSealReq) returns(DeleteSealResp) {
    option (api.post) = "/company/seal/delete";
  }
  rpc QueryEblTransferLog(QueryEblTransferLogReq) returns(QueryEblTransferLogResp) {
    option (api.post) = "/ebl/transfer/log";
  }
  rpc CreateCompanyUser(CreateCompanyUserReq) returns(CreateCompanyUserResp) {
    option (api.post) = "/company/user/create";
  }
}

enum CompanyType {
  Ship = 1;
  Bank = 2;
  Common = 3;
}

enum UserType {
  Admin = 1;
  EblMaker = 2;
  EblChecker = 3;
  EblSealer = 4;
  CompanyUser = 5;
}

enum OperationType {
  Submit = 1;
  Approve = 2;
  Reject = 3;
  Retreat = 4;
  Seal = 5;
  Issue = 6;
  AcceptIssue = 7;
  Transfer = 8;
  Redeem = 9;
  AcceptTransfer = 10;
  RefuseIssue = 11;
  RefuseTransfer = 12;
}

enum QueryEblType {
  Manage = 1;
  TransferIssue = 2;
  Accept = 3;
}

message Company {
  required int64 id = 1;
  required string company_code = 2;
  required string company_name = 3;
  required CompanyType company_type = 4;
}

message Ebl {
  required string eblNo = 1;
  required string originCompanyID = 2;
  required string originCompanyName = 3;
  required string shipperCompanyID = 4;
  required string shipperCompanyName = 5;
  required string consigneeCompanyID = 6;
  required string consigneeCompanyName = 7;
  required string notifyPartyCompanyID = 8;
  required string notifyPartyCompanyName = 9;
  required string placeOfReceipt = 10;
  required string oceanVessel = 11;
  required string portOfLoading = 12;
  required string portOfDescharge = 13;
  required string placeOfDestination = 14;
  required string placeOfDelivery = 15;
  required string shippingMarkes = 16;
  required double quantityOfPackages = 17;
  required string kindOfPackagesGW = 18;
  required string kindOfPackagesM = 19;
  required string descriptionOfGoods = 20;
  required double grossWeight = 21;
  required double measurement = 22;
  required string freightAndCharges = 23;
  required string placeOfIssue = 24;
  required int64 dateOfIssue = 25;
  required string deliveryAgent = 26;
  required int64 shippedOnBoard = 27;
  required int64 numOfEbl = 28;
  required int64 dateOfIssueDeadline = 29;
  required string status = 30;
  required string file = 31;
  repeated int64 contractFiles = 32;
  repeated int64 invoiceFiles = 33;
  required string transferCompanyID = 34;
  required string transferCompanyName = 35;
  required string companyID = 36;
  required string companyName = 37;
  repeated int64 documentFiles = 38;
}

message EblTransferLog {
  required string transFerEblNo = 1;
  required string transferFromCompanyID = 2;
  required string transferFromCompanyName = 3;
  required string transferToCompanyID = 4;
  required string transferToCompanyName = 5;
  required int64 transferTime = 6;
  required string transferType = 7;
}

message EblFilter {
  required string eblNo = 1;
  required string originCompanyID = 2;
  required string shipperCompanyID = 3;  // 原4→3
  required string consigneeCompanyID = 4; // 原6→4
  required string notifyPartyCompanyID = 5; // 原8→5
  required string placeOfReceipt = 6;     // 原10→6
  required string oceanVessel = 7;        // 原11→7
  required string portOfLoading = 8;      // 原12→8
  required string portOfDescharge = 9;   // 原13→9
  required string placeOfDestination = 10; // 原14→10
  required string placeOfDelivery = 11;   // 原15→11
  required string shippingMarkes = 12;    // 原16→12
  required double quantityOfPackages = 13; // 原17→13
  required string kindOfPackagesGW = 14; // 原18→14
  required string kindOfPackagesM = 15;   // 原19→15
  required string descriptionOfGoods = 16; // 原20→16
  required double grossWeight = 17;       // 原21→17
  required double measurement = 18;       // 原22→18
  required string freightAndCharges = 19; // 原23→19
  required string placeOfIssue = 20;      // 原24→20
  required int64 dateOfIssue = 21;        // 原25→21
  required string deliveryAgent = 22;     // 原26→22
  required int64 shippedOnBoard = 23;     // 原27→23
  required int64 numOfEbl = 24;           // 原28→24
  required int64 dateOfIssueDeadline = 25;// 原29→25
  required string status = 26;            // 原30→26
  required string transferCompanyID = 27; // 原34→27
  required string companyID = 28;         // 原36→28
}

message EblExtra {
  required string eblNo = 1;
  required string originCompanyID = 2;
  required string originCompanyName = 3;
  required string shipperCompanyID = 4;
  required string shipperCompanyName = 5;
  required string consigneeCompanyID = 6;
  required string consigneeCompanyName = 7;
  required string notifyPartyCompanyID = 8;
  required string notifyPartyCompanyName = 9;
  required string placeOfReceipt = 10;
  required string oceanVessel = 11;
  required string portOfLoading = 12;
  required string portOfDescharge = 13;
  required string placeOfDestination = 14;
  required string placeOfDelivery = 15;
  required string shippingMarkes = 16;
  required double quantityOfPackages = 17;
  required string kindOfPackagesGW = 18;
  required string kindOfPackagesM = 19;
  required string descriptionOfGoods = 20;
  required double grossWeight = 21;
  required double measurement = 22;
  required string freightAndCharges = 23;
  required string placeOfIssue = 24;
  required int64 dateOfIssue = 25;
  required string deliveryAgent = 26;
  required int64 shippedOnBoard = 27;
  required int64 numOfEbl = 28;
  required int64 dateOfIssueDeadline = 29;
  required string status = 30;
  required string file = 31;
  repeated Contract contractFiles = 32;
  repeated Invoice invoiceFiles = 33;
  required string transferCompanyID = 34;
  required string transferCompanyName = 35;
  required string companyID = 36;
  required string companyName = 37;
  repeated Document documentFiles = 38;
}

message Invoice {
  required string InvoiceNumber = 1;
  required double Amount = 2;
  required int64 IssueDate = 3;
  required InvoiceType Type = 4;
  required string FileHash = 5;
  optional string extra = 6;
  optional int64 CreatedAt = 7;
  optional int64 UpdatedAt = 8;
  required int64 Id = 9;
  required string Name = 10;
}

message InvoiceFilter {
  optional string InvoiceNumber = 1;
  optional double Amount = 2;
  optional int64 IssueDate = 3;
  optional InvoiceType Type = 4;
  optional string FileHash = 5;
  optional string Name = 6;
}

message Contract {
  required string ContractNumber = 1;
  required int64 SignDate = 2;
  required int64 EffectiveDate = 3;
  required double Amount = 4;
  required ContractStatus Status = 5;
  required string FileHash = 6;
  optional string extra = 7;
  optional int64 CreatedAt = 8;
  optional int64 UpdatedAt = 9;
  required int64 Id = 10;
  required string Name = 11;
}

message ContractFilter {
  optional string ContractNumber = 1;
  optional int64 SignDate = 2;
  optional int64 EffectiveDate = 3;
  optional double Amount = 4;
  optional ContractStatus Status = 5;
  optional string FileHash = 6;
  optional string Name = 7;
}

message Document {
  required DocType DocType = 1;
  required string DocNumber = 2;
  required int64 RelatedDate = 3;
  required string FileHash = 4;
  optional string extra = 5;
  optional int64 CreatedAt = 6;
  optional int64 UpdatedAt = 7;
  required int64 Id = 8;
  required string Name = 9;
}

message DocumentFilter {
  optional DocType DocType = 1;
  optional string DocNumber = 2;
  optional int64 RelatedDate = 3;
  optional string FileHash = 4;
  optional string Name = 5;
}

message CompanySeal {
  required int64 id = 1;
  required string name = 2;
  required bytes seal = 3;
  required string url = 4;
  optional int64 created_at = 5;
  optional int64 updated_at = 6;
  optional int64 deleted_at = 7;
  required int64 company_id = 8;
}

enum InvoiceType {
  Electronic = 1;
  Paper = 2;
}

enum ContractStatus {
  Active = 1;
  Terminated = 2;
}

enum DocType {
  StorageIn = 1;
  StorageOut = 2;
  Settlement = 3;
}