syntax = "proto2";

package miner_api;

option go_package = "miner_api";

import "api.proto";

message SignUpReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}

message SignUpResp {
  required int64 code = 1;
  required string message = 2;
  optional SignUpData data = 3;
}

message SignUpData {
  required int64 id = 1;
}

message QueryJobListReq {
  // 分页参数
  required int64 page_num = 1[(api.body)="page_num"];
  required int64 page_size = 2[(api.body)="page_size"];
  optional JobColumn order_by = 3[(api.body)="order_by"];
  optional Order order = 4[(api.body)="order"];

  // 过滤条件
  optional int64 id = 5 [(api.body)="id"];
  optional int64 created_by = 6 [(api.body)="created_by"];
  optional int64 created_at_start = 7 [(api.body)="created_at_start"];
  optional int64 created_at_end = 8 [(api.body)="created_at_end"];
}

message QueryJobListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryJobListData data = 3;
}

message QueryJobListData {
  repeated Job job_list = 1;
  required int64 total = 2;
}

service MinerApi {
  rpc SignUp(SignUpReq) returns(SignUpResp) {
    option (api.post) = "/user/signup";
  }
  rpc QueryJobList(QueryJobListReq) returns(QueryJobListResp) {
    option (api.post) = "/job/query/list";
  }
}

enum Order {
    DESC = 0;
    ASC = 1;
}

enum JobColumn {
    ID = 0;
    NAME = 1;
    DESCRIPTION = 2;
    CREATED_BY = 3;
    UPDATED_BY = 4;
    CREATED_AT = 5;
    UPDATED_AT = 6;
    EXTRA = 7;
}

message Job {
  required int64 id = 1;
  required string name = 2;
  required string description = 3;
  required int64 created_by = 4;
  required int64 updated_by = 5;
  required int64 created_at = 6;
  required int64 updated_at = 7;
  optional string extra = 8;
}
