syntax = "proto2";

package miner_api;

option go_package = "miner_api";

import "api.proto";

message LoginReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}
message LoginResp {
  required int64 code = 1;
  required string message = 2;
  optional LoginData data = 3;
}

message LoginData {
  required string token = 1;
}

message SignUpReq {
  required string email = 1[(api.body)="email"];
  required string password = 2[(api.body)="password"];
}

message SignUpResp {
  required int64 code = 1;
  required string message = 2;
  optional SignUpData data = 3;
}

message QueryUserListReq {

}
message QueryUserListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryUserListData data = 3;
}

message QueryUserListData {
  repeated User user_list = 1;
}

message SignUpData {
  required int64 id = 1;
}

message QueryJobListReq {
  // 分页参数
  required int64 page_num = 1[(api.body)="page_num"];
  required int64 page_size = 2[(api.body)="page_size"];
  optional JobColumn order_by = 3[(api.body)="order_by"];
  optional Order order = 4[(api.body)="order"];

  // 过滤条件
  optional int64 id = 5 [(api.body)="id"];
  optional string name = 6 [(api.body)="name"];
  optional int64 created_by = 7 [(api.body)="created_by"];
  optional int64 created_at_start = 8 [(api.body)="created_at_start"];
  optional int64 created_at_end = 9 [(api.body)="created_at_end"];
}

message QueryJobListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryJobListData data = 3;
}

message QueryJobListData {
  repeated Job job_list = 1;
  required int64 total = 2;
}

message CreateJobReq {
  required string name = 1[(api.body)="name"];
  optional string description = 2[(api.body)="description"];
}

message CreateJobResp {
  required int64 code = 1;
  required string message = 2;
  optional CreateJobData data = 3;
}

message CreateJobData {
  required int64 id = 1;
}

message DeleteJobReq {
  required int64 id = 1;
}

message DeleteJobResp {
  required int64 code = 1;
  required string message = 2;
  optional DeleteJobData data = 3;
}

message DeleteJobData {
}

message QueryIndicatorListReq {

}

message QueryIndicatorListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryIndicatorListData data = 3;
}

message QueryIndicatorListData {
  repeated FirstLevelIndicator indicators = 1;
}

message QueryTaskListReq {
  required int64 page_num = 1[(api.body)="page_num"];
  required int64 page_size = 2[(api.body)="page_size"];

  optional int64 job_id = 3[(api.body)="job_id"];
}

message QueryTaskListResp {
  required int64 code = 1;
  required string message = 2;
  optional QueryTaskListData data = 3;
}

message QueryTaskListData {
  repeated Task task_list = 1;
  required int64 total = 2;
}

message RunTaskReq {
  required int64 job_id = 1;
  repeated Rule rules = 2;
  required string logic_expression = 3;
  required int64 limit = 4;
}

message RunTaskResp {
  required int64 code = 1;
  required string message = 2;
  optional RunTaskData data = 3;
}

message RunTaskData {

}

service MinerApi {
  rpc Login(LoginReq) returns(LoginResp) {
    option (api.post) = "/user/login";
  }
  rpc SignUp(SignUpReq) returns(SignUpResp) {
    option (api.post) = "/user/signup";
  }
  rpc QueryUserList(QueryUserListReq) returns(QueryUserListResp) {
    option (api.get) = "/user/query/list";
  }
  rpc QueryJobList(QueryJobListReq) returns(QueryJobListResp) {
    option (api.post) = "/job/query/list";
  }
  rpc CreateJob(CreateJobReq) returns(CreateJobResp) {
    option (api.post) = "/job/create";
  }
  rpc DeleteJob(DeleteJobReq) returns(DeleteJobResp) {
    option (api.post) = "/job/delete";
  }
  rpc QueryIndicatorList(QueryIndicatorListReq) returns(QueryIndicatorListResp) {
    option (api.get) = "/indicator/query/list";
  }
  rpc QueryTaskList(QueryTaskListReq) returns(QueryTaskListResp) {
    option (api.post) = "/task/query/list";
  }
  rpc RunTask(RunTaskReq) returns(RunTaskResp) {
    option (api.get) = "/task/run";
  }
}

enum TaskStatus {
  Running = 1;
  Success = 2;
  Failed = 3;
}

enum InputElType {
  Unknown = 0;
  InputTag = 1;
  Input = 2;
  Select = 3;
}

enum Order {
    DESC = 0;
    ASC = 1;
}

enum JobColumn {
    ID = 0;
    NAME = 1;
    DESCRIPTION = 2;
    CREATED_BY = 3;
    UPDATED_BY = 4;
    CREATED_AT = 5;
    UPDATED_AT = 6;
    EXTRA = 7;
}

message Job {
  required int64 id = 1;
  required string name = 2;
  required string description = 3;
  required User created_by = 4;
  required User updated_by = 5;
  required int64 created_at = 6;
  required int64 updated_at = 7;
  optional string extra = 8;
}

message User {
  required int64 id = 1;
  required string email = 2;
}

message FirstLevelIndicator {
  required string display_name = 1;
  repeated SecondLevelIndicator children = 2;
}

message SecondLevelIndicator {
  required string factor_code = 1;
  required string display_name = 2;
  repeated AllowOperators allow_operators = 3;
}

message AllowOperators {
  required string operator_code = 1;
  required string display_name = 2;
  required InputElType input_el_type = 3;
  repeated AllowValues allow_values = 4;
}

message AllowValues {
  required string display_name = 1;
  required string value = 2;
}

message Task {
  required int64 id = 1;
  required int64 job_id = 2;
  required string name = 3;
  optional int64 total_records = 4;
  required TaskStatus status = 5;
  required User created_by = 6;
  required int64 created_at = 7;
  optional int64 time_cost = 8;
  repeated Rule rules = 9;
  required string logic_expression = 10;
  required int64  limit = 11;
  optional string extra = 12;
}

message Rule {
  required int64 id  = 1;
  required string factor_code  = 2;
  required string operator_code  = 3;
  repeated string value_list  = 4;
}