on:
  push:
    branches:
      - main

jobs:
  my_job:
    name: kitex gen
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install Kitex
        run: go install github.com/cloudwego/kitex/tool/cmd/kitex@latest

      - name: Generate Kitex code
        run: kitex -module core core.thrift

      - name: Configure git
        run: |
          git config --global user.name 'wxl'
          git config --global user.email '1715142548@qq.com'

      - name: Commit generated code
        run: |
          git add kitex_gen/*
          git add go.mod
          git commit -m 'Generate Kitex code'

      - name: Push to another repository
        env:
          ACCESS_TOKEN: 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
        run: |
          git remote add target https://github.com/qcq1/miner-core-gen.git
          git push --force target main