on:
  push:
    branches: [ "*" ]
    paths:
      - 'rpc_idl/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Trigger Kitex Gen
          run: |
            branch=$(echo ${{ github.event.ref }} | awk -F '/' '{print $3}')
            token=${{ secrets.TOKEN }}
            repo=${{ github.repository }}
            commit_msg=${{ github.event.head_commit.message }}
            # 检查是否存在 HEAD^
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              idls=$(git diff --name-only HEAD^ HEAD | grep -E 'rpc_idl/.*\.thrift$')
            else
              idls=$(git diff --name-only HEAD | grep -E 'rpc_idl/.*\.thrift$')
            fi
            sh ./trigger.sh