on:
  push:
    branches:
      - main

jobs:
  my_job:
    name: kitex gen
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install Kitex
        run: go install github.com/cloudwego/kitex/tool/cmd/kitex@latest

      - name: Generate Kitex code
        run: kitex -module core core.thrift

      - name: Configure git
        run: |
          git config --global user.name 'wxl'
          git config --global user.email '1715142548@qq.com'

      - name: Push to another repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: 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
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          repository: https://github.com/qcq1/miner-core-gen.git
          # Destination branch to push changes
          branch: main
          # Determines if force push is used
          force: true
          # Determines if --tags is used
          directory:
            - kitex_gen/*
            - go.mod